final List<String> quotes = [
  "Stay away from drugs – protect your mind and body.",
  "Mental health is just as important as physical health.",
  "Take time for yourself, your mind deserves rest.",
  "Your mental health matters – prioritize self-care.",
  "Reach out to others – connection helps you heal.",
  "Keep your mind active, but give it space to breathe.",
  "A healthy mind starts with healthy habits.",
  "Positive thoughts lead to positive actions.",
  "Self-care is not selfish; it's essential.",
  "Take a deep breath – calm your mind and heart.",
  "Mental wellness starts with positive thinking.",
  "Talk about your feelings – it’s a sign of strength.",
  "You are more than your thoughts; you control them.",
  "It's okay not to be okay. Seek help when needed.",
  "Your mental health should always be a priority.",
  "Small steps every day can lead to big changes.",
  "Rest and recharge – your mind deserves it.",
  "Kindness towards yourself is the best form of self-care.",
  "Balance your mind, body, and soul for true well-being.",
  "Happiness is an inside job – work on yourself.",
  "Find peace in the little moments.",
  "Healing is not linear; take one day at a time.",
  "You are worthy of love and happiness.",
  "Meditation is the medicine for the mind.",
  "Every emotion is valid – give yourself permission to feel.",
  "You don’t have to carry the weight of the world alone.",
  "Progress is still progress, no matter how slow.",
  "Mental health is a journey, not a destination.",
  "Be gentle with yourself; you're doing the best you can.",
  "Letting go of the past is the first step to healing.",
  "Your mental health is your greatest wealth.",
  "It’s okay to ask for help – you don’t have to do it alone.",
  "Nourish your mind with positivity and calm.",
  "Healing begins when you choose to prioritize your well-being.",
  "You are stronger than you think – take it one step at a time.",
  "Your mind is a garden; take care of it.",
  "Stress is temporary, but your health is forever.",
  "Breathe deeply – find peace in this moment.",
  "The greatest investment is in your mental health.",
  "You are not alone – reach out, and there’s help.",
  "Every day is a new opportunity for healing and growth.",
  "You are not your thoughts – observe, don’t absorb.",
  "Mental health is a priority, not a luxury.",
  "Small acts of self-care lead to big improvements.",
  "Your well-being matters – take time to nurture it.",
  "Taking care of yourself is productive.",
  "Peace of mind is the true measure of success.",
  "Healing takes time, but it is worth the effort.",
  "A calm mind is a powerful mind.",
  "You deserve to feel good, mentally and emotionally."
];
